name: 新功能请求 (新機能のリクエスト / Feature Request)
description: 告知我们你还需要什么 (必要な機能があればお知らせください / Tell us what else you need)
labels: []
body:
  - type: markdown
    attributes:
      value: |
        不要感到有压力：对我们来说，有东西做总会比没有东西做要好。但是我们仍需要对请求进行评估，并非所有新功能请求都会被批准。
        私たちにとっては、やれることがあることは進歩のもと。ただし、リクエストは仕様確認される必要がありますので、すべての新機能リクエストが開発リストに移されるわけではありません。
        Don't feel pressured: For us, having something to do is always better than having nothing to do. But we still need to evaluate the requests, not all new feature requests will be approved.
  - type: textarea
    id: background
    attributes:
      label: 简述 (説明 / Description)
      description: |
        请分享一个清晰简洁的描述。
        明確で簡潔な説明を記入してください。
        Please share a clear and concise description.
      placeholder: Description
    validations:
      required: true
  - type: textarea
    id: available-refers
    attributes:
      label: 可供参考 (参考になれるもの / Available References)
      description: |
        如果有其他类似的程序/网站已经实现了这个功能，请在这里分享。
        もし他の類似のアプリやウェブサイトでこの機能がすでに実装されている場合は、ここに共有してください。
        If there are other similar programs/websites that have already implemented this feature, please share it here.
      placeholder: Related Versions
    validations:
      required: false