name: Build and Deploy
# 监听 master 分支上的 push 事件
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    # 构建环境使用 ubuntu
    runs-on: ubuntu-latest
    steps:
      # 官方action, 将代码拉取到虚拟机
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      # 安装node.js
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.8.1"

      # 下载依赖、打包项目
      - name: Install and Build
        run: |
          yarn install
          yarn build

      # 部署
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          # 项目配置的打包目录名称
          folder: dist
          # 部署后提交到的分支
          branch: static-pages

      # 打包构建输出为zip文件
      - name: Zip Static Pages
        run: |
          zip -r static-pages.zip dist

      # 获取 package.json 中的版本号
      - name: Get Version from package.json
        id: get_version
        run: echo "VERSION=$(jq -r .version < package.json)" >> $GITHUB_ENV

      # 检查是否存在同版本的 Release
      - name: Check for Existing Release
        id: check_release
        run: |
          if gh release view "v${{ env.VERSION }}" > /dev/null 2>&1; then
            echo "exists=true" >> $GITHUB_ENV
          else
            echo "exists=false" >> $GITHUB_ENV
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 创建或更新 Release
      - name: Create or Update Release
        run: |
          if [ "${{ env.exists }}" = "true" ]; then
            gh release upload "v${{ env.VERSION }}" static-pages.zip --clobber
          else
            gh release create "v${{ env.VERSION }}" static-pages.zip --title "Release v${{ env.VERSION }}"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
